title: Axel Buob
email: buobaxel@gmail.com
description: >-
  Frontend web developper

baseurl: "/"
url: "http://axelbuob.github.io"
permalink: /:categories/:title
include: ['_pages']

sass:
  sass_dir: _sass
  style: compressed
  
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - github-pages

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .DS_Store






